# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "seeed_xiao_ble", "nice_nano_v2" ]
# shield: [ "twenny_left", "twenny_right", "lebroke" ]
#
#  - board: seeeduino_xiao_ble
#    shield: twenny_left
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#  - board: seeeduino_xiao_ble
#    shield: twenny_right
#  - board: nice_nano_v2
#    shield: lebroke
#    snippet: studio-rpc-usb-uart
#    snippet: zmk-usb-logging
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#  - board: nice_nano_v2
#    shield: settings_reset
---
include:
  - board: seeeduino_xiao_ble
    shield: twenny_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: twenny_right
  - board: seeeduino_xiao_ble
    shield: pocketpilot
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: lebroke
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset
