# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "seeed_xiao_ble", "nice_nano_v2" ]
# shield: [ "twenny_left", "twenny_right", "twenny_dongle", "lebroke", "ocarina", "pocketpilot", "wakizashi", "pueo_left", "pueo_right", "swagboard_left", "swagboard_right" ]
#
#  - board: seeeduino_xiao_ble
#    shield: settings_reset
#  - board: nice_nano_v2
#    shield: settings_reset
#
#
#  - board: seeeduino_xiao_ble
#    shield: pocketpilot
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#
#  - board: nice_nano_v2
#    shield: lebroke
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#
#  - board: nice_nano_v2
#    shield: ocarina
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#
#  - board: nice_nano_v2
#    shield: wakizashi
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#
# - board: seeeduino_xiao_ble
#   shield: twenny_dongle
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: seeeduino_xiao_ble
#   shield: twenny_left
#   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
# - board: seeeduino_xiao_ble
#   shield: twenny_right
#   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#
# - board: nice_nano_v2
#   shield: pueo_dongle
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano_v2
#   shield: pueo_left
#   snippet: studio-rpc-usb-uart
#   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
# - board: nice_nano_v2
#   shield: pueo_right
#   snippet: studio-rpc-usb-uart
#   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
#
# - board: seeeduino_xiao_ble
#   shield: swagboard_dongle nice_swagboard nice_epaper
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano_v2
#   shield: swagboard_left nice_swagboard nice_epaper
#   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
# - board: nice_nano_v2
#   shield: swagboard_right nice_swagboard nice_epaper
#   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
---
include:
 - board: seeeduino_xiao_ble
   shield: pueo_dongle
   cmake-args: -DCONFIG_ZMK_STUDIO=y
 - board: nice_nano_v2
   shield: swagboard_left nice_swagboard nice_epaper
   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
 - board: nice_nano_v2
   shield: swagboard_right nice_swagboard nice_epaper
   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
